# -*- coding: utf-8 -*-
"""Transformer 10fold validation thermo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13x90OQutG-2M-jD6MVuFedFnxznbCbBk
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from transformers import AutoTokenizer, EsmModel
from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score, balanced_accuracy_score, confusion_matrix,
                             f1_score, precision_score, matthews_corrcoef, recall_score, roc_curve, auc)
import matplotlib.pyplot as plt
import numpy as np

!pip install -q transformers torch sklearn matplotlib seaborn

# Pip aur setuptools ko pehle upgrade karein taake metadata error na aaye
!pip install --upgrade pip setuptools wheel

# 'sklearn' ki bajaye 'scikit-learn' install karein
!pip install -q transformers torch scikit-learn matplotlib seaborn

# =========================
# 1. IMPORTS
# =========================
import os
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, EsmModel
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (accuracy_score, confusion_matrix,
                             f1_score, precision_score, recall_score,
                             matthews_corrcoef, roc_curve, auc)

# =========================
# 2. CONFIG
# =========================
MODEL_NAME_TAG = "transformer10fold_crossvalidation"
MODEL_PATH = MODEL_NAME_TAG + ".pth"
ROC_PATH = "transformer10fold_roc_data.npz"

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# =========================
# 3. LOAD DATA
# =========================
def parse_fasta(path):
    seqs = []
    with open(path, 'r') as f:
        current = ""
        for line in f:
            if line.startswith(">"):
                if current:
                    seqs.append(current)
                current = ""
            else:
                current += line.strip()
        if current:
            seqs.append(current)
    return seqs

thermo = parse_fasta('/content/0.6thermo.fasta')
non_thermo = parse_fasta('/content/0.6 non thermo.fasta')

X = np.array(thermo + non_thermo)
y = np.array([1]*len(thermo) + [0]*len(non_thermo))

# =========================
# 4. TOKENIZER
# =========================
model_name = "facebook/esm2_t6_8M_UR50D"
tokenizer = AutoTokenizer.from_pretrained(model_name)

class ProteinDataset(Dataset):
    def __init__(self, seqs, labels):
        self.labels = labels
        self.encodings = tokenizer(list(seqs), padding=True, truncation=True,
                                   max_length=512, return_tensors="pt")

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {k: v[idx] for k, v in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.float32)
        return item

# =========================
# 5. MODEL
# =========================
class ESMClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.esm = EsmModel.from_pretrained(model_name)
        self.classifier = nn.Linear(320, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, input_ids, attention_mask):
        outputs = self.esm(input_ids=input_ids, attention_mask=attention_mask)
        pooled = outputs.last_hidden_state.mean(dim=1)
        return self.sigmoid(self.classifier(pooled))

# =========================
# 6. LOAD OR TRAIN
# =========================
if os.path.exists(MODEL_PATH):
    print("Loading saved Transformer model...")
    model = ESMClassifier().to(device)
    model.load_state_dict(torch.load(MODEL_PATH))

else:
    print("Training Transformer with 10-Fold CV...")

    kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

    acc_list, f1_list, mcc_list = [], [], []
    precision_list, recall_list = [], []
    conf_matrix = np.array([[0,0],[0,0]])

    all_probs = []
    all_true = []

    fold = 1

    for train_idx, test_idx in kf.split(X, y):
        print(f"\nFold {fold}/10")

        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]

        train_loader = DataLoader(ProteinDataset(X_train, y_train), batch_size=8, shuffle=True)
        test_loader = DataLoader(ProteinDataset(X_test, y_test), batch_size=8)

        model = ESMClassifier().to(device)
        optimizer = optim.AdamW(model.parameters(), lr=1e-5)
        criterion = nn.BCELoss()

        # TRAIN
        for epoch in range(3):
            model.train()
            for batch in train_loader:
                input_ids = batch['input_ids'].to(device)
                mask = batch['attention_mask'].to(device)
                labels = batch['labels'].to(device)

                optimizer.zero_grad()
                outputs = model(input_ids, mask).squeeze()
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()

        # TEST
        model.eval()
        probs, true = [], []

        with torch.no_grad():
            for batch in test_loader:
                input_ids = batch['input_ids'].to(device)
                mask = batch['attention_mask'].to(device)

                outputs = model(input_ids, mask).squeeze()
                probs.extend(outputs.cpu().numpy())
                true.extend(batch['labels'].numpy())

        preds = (np.array(probs) > 0.5).astype(int)

        cm = confusion_matrix(true, preds)
        conf_matrix += cm

        acc_list.append(accuracy_score(true, preds))
        f1_list.append(f1_score(true, preds))
        precision_list.append(precision_score(true, preds))
        recall_list.append(recall_score(true, preds))
        mcc_list.append(matthews_corrcoef(true, preds))

        all_probs.extend(probs)
        all_true.extend(true)

        fold += 1

    # =========================
    # RESULTS
    # =========================
    print("\n===== TRANSFORMER 10-FOLD RESULTS =====")
    print(f"Accuracy: {np.mean(acc_list)*100:.4f}%")
    print(f"F1 Score: {np.mean(f1_list)*100:.4f}%")
    print(f"Precision: {np.mean(precision_list)*100:.4f}%")
    print(f"Recall: {np.mean(recall_list)*100:.4f}%")
    print(f"MCC: {np.mean(mcc_list):.4f}")
    print(f"Confusion Matrix:\n{conf_matrix}")

    # SAVE MODEL
    torch.save(model.state_dict(), MODEL_PATH)
    print("Model saved!")

    # =========================
    # ROC SAVE
    # =========================
    fpr_transf, tpr_transf, _ = roc_curve(all_true, all_probs)
    auc_transf = auc(fpr_transf, tpr_transf)

    np.savez(ROC_PATH,
             fpr_transf=fpr_transf,
             tpr_transf=tpr_transf,
             auc_transf=auc_transf)

    print("ROC data saved!")

# =========================
# 7. SEPARATE ROC PLOT
# =========================
data = np.load(ROC_PATH)

fpr_transf = data['fpr_transf']
tpr_transf = data['tpr_transf']
auc_transf = data['auc_transf']

plt.figure(figsize=(8,6))
plt.plot(fpr_transf, tpr_transf, label=f'Transformer (AUC = {auc_transf:.3f})')
plt.plot([0,1],[0,1],'--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Transformer 10-Fold ROC Curve")
plt.legend()
plt.show()

# =========================
# SAVE ROC DATA
# =========================
np.savez("transformer10fold_roc_data.npz",
         fpr_transf=fpr_transf,
         tpr_transf=tpr_transf,
         auc_transf=auc_transf)

print("ROC data saved as transformer10fold_roc_data.npz")

from google.colab import files
files.download("transformer10fold_roc_data.npz")



import numpy as np

data = np.load("transformer10fold_roc_data.npz")

fpr_transf = data['fpr_transf']
tpr_transf = data['tpr_transf']
auc_transf = data['auc_transf']

print("ROC Loaded Successfully!")

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
plt.plot(fpr_transf, tpr_transf, label=f'Transformer (AUC = {auc_transf:.3f})')
plt.plot([0,1],[0,1],'--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Transformer ROC Curve (Loaded from NPZ)")
plt.legend()
plt.show()